/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.irati.ads.visao;

/**
 *
 * @author Valter Estevam
 */
public class SimuladoGUI_esboco extends javax.swing.JFrame {

    /**
     * Creates new form SimuladoGUI
     */
    public SimuladoGUI_esboco() {
        initComponents(); 
        jCheckBoxOp16.setVisible(false);
        jCheckBoxOp32.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEscolhaQuestao = new javax.swing.JPanel();
        jComboBoxEscolhaQuestao = new javax.swing.JComboBox<>();
        jPanelComandos = new javax.swing.JPanel();
        jPanelComandosEsquerda = new javax.swing.JPanel();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jPanelComandosDireita = new javax.swing.JPanel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCorrigir = new javax.swing.JButton();
        jPanelElementosQuestao = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerda = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaDisciplina = new javax.swing.JPanel();
        jLabelDisciplina = new javax.swing.JLabel();
        jPanelElementosQuestaoEsquerdaEnunciado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelElementosQuestaoEsquerdaCentral = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaCentralCabecalho = new javax.swing.JPanel();
        jPanelElementosQuestaoEsquerdaCabecalhoNumero = new javax.swing.JPanel();
        jLabelNumeroQuestao = new javax.swing.JLabel();
        jPanelElementosQuestaoEsquerdaCabecalhoImagem = new javax.swing.JPanel();
        jButtonImagemQuestao = new javax.swing.JButton();
        jPanelElementosQuestaoEsquerdaCentralTexto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTextoQuestao = new javax.swing.JTextArea();
        jPanelElementosQuestaoDireita = new javax.swing.JPanel();
        jCheckBoxOp01 = new javax.swing.JCheckBox();
        jCheckBoxOp02 = new javax.swing.JCheckBox();
        jCheckBoxOp04 = new javax.swing.JCheckBox();
        jCheckBoxOp08 = new javax.swing.JCheckBox();
        jCheckBoxOp16 = new javax.swing.JCheckBox();
        jCheckBoxOp32 = new javax.swing.JCheckBox();
        jPanelElementosQuestaoDireitaSomatorio = new javax.swing.JPanel();
        jTextFieldSomatorio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEscolhaQuestao.setLayout(new java.awt.GridLayout(1, 0));

        jComboBoxEscolhaQuestao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelEscolhaQuestao.add(jComboBoxEscolhaQuestao);

        getContentPane().add(jPanelEscolhaQuestao, java.awt.BorderLayout.PAGE_START);

        jPanelComandos.setLayout(new java.awt.GridLayout(1, 2));

        jPanelComandosEsquerda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButtonAnterior.setText("<");
        jButtonAnterior.setToolTipText("Ir para a questão anterior");
        jPanelComandosEsquerda.add(jButtonAnterior);

        jButtonProximo.setText(">");
        jButtonProximo.setToolTipText("Ir para a próxima questão.");
        jPanelComandosEsquerda.add(jButtonProximo);

        jPanelComandos.add(jPanelComandosEsquerda);

        jPanelComandosDireita.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("Limpar as respostas da questão.");
        jPanelComandosDireita.add(jButtonLimpar);

        jButtonCorrigir.setText("Corrigir");
        jButtonCorrigir.setToolTipText("Corrigir a questão");
        jPanelComandosDireita.add(jButtonCorrigir);

        jPanelComandos.add(jPanelComandosDireita);

        getContentPane().add(jPanelComandos, java.awt.BorderLayout.PAGE_END);

        jPanelElementosQuestao.setLayout(new java.awt.GridLayout(1, 0));

        jPanelElementosQuestaoEsquerda.setLayout(new java.awt.BorderLayout());

        jLabelDisciplina.setText("Disciplina");
        jPanelElementosQuestaoEsquerdaDisciplina.add(jLabelDisciplina);

        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaDisciplina, java.awt.BorderLayout.PAGE_START);

        jPanelElementosQuestaoEsquerdaEnunciado.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanelElementosQuestaoEsquerdaEnunciado.add(jScrollPane2);

        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaEnunciado, java.awt.BorderLayout.PAGE_END);

        jPanelElementosQuestaoEsquerdaCentral.setLayout(new java.awt.BorderLayout());

        jPanelElementosQuestaoEsquerdaCentralCabecalho.setLayout(new java.awt.GridLayout(1, 0));

        jPanelElementosQuestaoEsquerdaCabecalhoNumero.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelNumeroQuestao.setText("Questão 1");
        jPanelElementosQuestaoEsquerdaCabecalhoNumero.add(jLabelNumeroQuestao);

        jPanelElementosQuestaoEsquerdaCentralCabecalho.add(jPanelElementosQuestaoEsquerdaCabecalhoNumero);

        jPanelElementosQuestaoEsquerdaCabecalhoImagem.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonImagemQuestao.setText("Ver imagem");
        jPanelElementosQuestaoEsquerdaCabecalhoImagem.add(jButtonImagemQuestao);

        jPanelElementosQuestaoEsquerdaCentralCabecalho.add(jPanelElementosQuestaoEsquerdaCabecalhoImagem);

        jPanelElementosQuestaoEsquerdaCentral.add(jPanelElementosQuestaoEsquerdaCentralCabecalho, java.awt.BorderLayout.PAGE_START);

        jPanelElementosQuestaoEsquerdaCentralTexto.setLayout(new java.awt.GridLayout(1, 0));

        jTextAreaTextoQuestao.setColumns(20);
        jTextAreaTextoQuestao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTextoQuestao);

        jPanelElementosQuestaoEsquerdaCentralTexto.add(jScrollPane1);

        jPanelElementosQuestaoEsquerdaCentral.add(jPanelElementosQuestaoEsquerdaCentralTexto, java.awt.BorderLayout.CENTER);

        jPanelElementosQuestaoEsquerda.add(jPanelElementosQuestaoEsquerdaCentral, java.awt.BorderLayout.CENTER);

        jPanelElementosQuestao.add(jPanelElementosQuestaoEsquerda);

        jPanelElementosQuestaoDireita.setLayout(new java.awt.GridLayout(7, 1));

        jCheckBoxOp01.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp01);

        jCheckBoxOp02.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp02);

        jCheckBoxOp04.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp04);

        jCheckBoxOp08.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp08);

        jCheckBoxOp16.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp16);

        jCheckBoxOp32.setText("...");
        jPanelElementosQuestaoDireita.add(jCheckBoxOp32);

        jPanelElementosQuestaoDireitaSomatorio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jTextFieldSomatorio.setEditable(false);
        jTextFieldSomatorio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextFieldSomatorio.setText("      ");
        jTextFieldSomatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSomatorioActionPerformed(evt);
            }
        });
        jPanelElementosQuestaoDireitaSomatorio.add(jTextFieldSomatorio);

        jPanelElementosQuestaoDireita.add(jPanelElementosQuestaoDireitaSomatorio);

        jPanelElementosQuestao.add(jPanelElementosQuestaoDireita);

        getContentPane().add(jPanelElementosQuestao, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSomatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSomatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSomatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladoGUI_esboco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladoGUI_esboco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladoGUI_esboco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladoGUI_esboco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladoGUI_esboco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCorrigir;
    private javax.swing.JButton jButtonImagemQuestao;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JCheckBox jCheckBoxOp01;
    private javax.swing.JCheckBox jCheckBoxOp02;
    private javax.swing.JCheckBox jCheckBoxOp04;
    private javax.swing.JCheckBox jCheckBoxOp08;
    private javax.swing.JCheckBox jCheckBoxOp16;
    private javax.swing.JCheckBox jCheckBoxOp32;
    private javax.swing.JComboBox<String> jComboBoxEscolhaQuestao;
    private javax.swing.JLabel jLabelDisciplina;
    private javax.swing.JLabel jLabelNumeroQuestao;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelComandosDireita;
    private javax.swing.JPanel jPanelComandosEsquerda;
    private javax.swing.JPanel jPanelElementosQuestao;
    private javax.swing.JPanel jPanelElementosQuestaoDireita;
    private javax.swing.JPanel jPanelElementosQuestaoDireitaSomatorio;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerda;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCabecalhoImagem;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCabecalhoNumero;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentral;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentralCabecalho;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaCentralTexto;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaDisciplina;
    private javax.swing.JPanel jPanelElementosQuestaoEsquerdaEnunciado;
    private javax.swing.JPanel jPanelEscolhaQuestao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaTextoQuestao;
    private javax.swing.JTextField jTextFieldSomatorio;
    // End of variables declaration//GEN-END:variables
}
